language: python

python:
  - "3.6"

branches:
  only:
    - master

before_script:
  - openssl aes-256-cbc -K $encrypted_bfa1e34e2ba5_key -iv $encrypted_bfa1e34e2ba5_iv -in .travis/deploy.enc -out "$HOME/.ssh/deploy" -d
  - chmod 600 "$HOME/.ssh/deploy"
  - echo -e "Host github.com\n\tIdentityFile $HOME/.ssh/deploy\n" >> $HOME/.ssh/config
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "$GIT_NAME"

script:
  - git clone "git@github.com:$TRAVIS_REPO_SLUG.wiki" .wiki
  - python3 .travis/wiki.py
  - cd .wiki
  - git add .
  - git commit -m "$TRAVIS_COMMIT"
  - git push origin master

env:
  global:
    - secure: WIE/pramTCcTVElGyLZ0oGallWz1frBrPLq4Bf3d/B/+oRePk2TvfS7iNQKx1P+EzIS3buf82e85iartH0G5Ybu7WTIwWCK8F551+3rdqM6XswGqiKcLjwzp5K4pRyiT7hD0suDWwX4QmCPe94YjPrN1yrIcdW5qSrzcDStd2iPCCwWX01g6zUj580/JxTAXDtjIPHeHFXVIXgJre8wvGdcjg0BEIASRoXod9BUv6AMv+BqIB/P4RkIpkuT1BbhBqil4QyEL2Yn3Umk/q3XTiLqraVzh9gmXk/FxwRKy4Qa86GQJWDA8qZevRCuOBDksnd7IcpwVNGEoMvzL7G8QkrO3+tRrCzUxxjXRFii1XBsiZB5sL+Wi+YyBwO0iMUjaBNBT6xs1oBQV0R4Q/y8xMR/WSDq2as5THIB/uzL+lBlxm2HQsAEHfFKGzHwd0V1+DuCYyhHnLnTcZt2HbiEusGODwpE4v043nCT9vuQ6u4e8bcUA6In1TpApr3gS4KoXhd1CI/KUzTeRji3tPc7gSsDjYXkC+KaMZKS0czjCU+8DeUJsdaEM4tM4gXL4Zdz23iGGVDV0FuNIgd3sGBRodvHvbGFzPJQQ1BHHO3De9GExPc4HTycMV/BmZHKunzKwo2LBDy1c8zSvEorPouUI1RXCkbhm40/1Z/JaYkW6Bkk=
    - secure: oLMAkdMTcD2tuwtMK1IeLDDqjJWIy8p8P2dllVpHW2cWntMg/Gnsa5ftCxxN6Lsx/NUlTQADVHApk0v6+Kr5apINtvHSnd3V6GZCwviTiT5/B+1FiIPstcqA0TOzoP2F31SIBHuUYwsualWmAdzljEDq1fQqXAUUzpMj7xWHwnk8Z+OlXjbJhXiIi6AR169sfy2imf+SsJCvS+LTldFxBBSLdCZbOXzq3ujypZydv+8iSzv9NJCNecWvBJKGpDEIdS14B2DY3pYX3FWpG3tT4S5pk+hTwii0kCbtAksQr4xs1unlQ9NpL5hx3q0PU4c3QfksTUDVZTfHZG12qDJYjwIS1bpUKo+B5SiXynShwC41tU2jpV2iqiizZK+LXX339urEv7RynyZHm1DZ2+10KUJRHXvk2c80VnOOIw2TvTWAS5px4DJCY+E2MvyGjtjPkF1ZP7Q5f1hW/qpVHbVDZ0fJJVoCbYyxjjnukOoq+ElNPqy63TuM6W+FB5wkwuQtfqXPmcDSTBgdaimzJfDxGKjpFCWk+vyJt/WLML/9LoTO3CGVOYx7idFBOKhrH2z0KtLSglUCU1dAFY2xSCZgNQAR952SV8mS1lHqKczvwBZCEAcWjrNT+s5tIZ7aRn1CRScxMtvLrrSm+n5QYH8hl8Z1laJS8CdFHSGycwQRmpc=

notifications:
  email: false
