version: 2
jobs:
  docs:
    docker:
      - image: p3lim/lua-doc-parser:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:joVSe3jKLQ/D1ptVgXPHqGfCP0mN0LF0Q7+5zYABRvw"
      - checkout
      - run: build
  release:
    docker:
      - image: p3lim/wow-packager:latest
    steps:
      - checkout
      - run: release.sh
      - run: release.sh -g 1.13.3 -w 0
workflows:
  version: 2
  docs:
    jobs:
      - docs:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /.*/
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          context: api-keys
