name: Package and release
on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Package and release
        uses: BigWigsMods/packager@064e524

      - name: Package and release for Classic
        uses: BigWigsMods/packager@064e524
        with:
          args: -g 1.13.5 -w 0
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
